###############################################################################################
#########                           --Database Settings--                             #########
###############################################################################################
# dbprefix is currently unused
dbhost: 127.0.0.1:3306
dbname: emi
dbuser: emi
dbpass: 'secret'
dbprefix: 'ev_'

###############################################################################################
#########                              --Bot Settings--                               #########
###############################################################################################
### DEFAULTS ###
# ============ #
# bot-token: 'BOT-TOKEN-HERE' - replace this with your bot token from the developers portal
# bot-owner-id: 0 - Should belong to the owner of the guild or bot creator (if not owner of guild)
# bot-status: 'EMI' - Change what the bot is set as watching ("Watching EMI")
bot-token: 'BOT-TOKEN-HERE'
bot-owner-id: 0
guild-id: 0
bot-status: 'EMI'

###############################################################################################
#########                            --Channel/Role Ids--                             #########
###############################################################################################
# announcement-channel-id: 0 - The channel in which whitelist announcements should be made

staff-channel-id: 0
voting-channel-id: 0
announcement-channel-id: 0
mint-channel-id: 0

applicant-role-id: 0
pending-role-id: 0
synced-role-id: 0
member-role-id: 0
mint-role-id: 0
staff-role-id: 0

# root-help-msg: 0 - Message to preserve in report channel (IE: rules/info message at start of channel)
help-channel-id: 0
root-help-msg: 0

###############################################################################################
#########                              --EMI Settings--                               #########
###############################################################################################
chat-tag: '&7[&6EMI&7]'
items-per-page: 0