name: EMI
version: 1.3.1
main: com.everneth.emi.EMI
author: tptmike, sterling
api-version: 1.17
commands:
  emi:
    description: Ministry Interface version
    usage: /emi
  int:
    description: Ministry of the Interior Toolkit
    usage: /mint
  comp:
    description: Ministry of Competition Toolkit
    usage: /comp
  comm:
    description: Ministry of Communications Toolkit
    usage: /comm