name: EMI
version: 2.1.2
main: com.everneth.emi.EMI
author: tptmike, sterling, jmwren
api-version: 1.20
commands:
  emi:
    description: Ministry Interface version
    usage: /emi
  int:
    description: Ministry of the Interior Toolkit
    usage: /mint
  comp:
    description: Ministry of Competition Toolkit
    usage: /comp
  comm:
    description: Ministry of Communications Toolkit
    usage: /comm
